---
- name: Converge
  hosts: all
  gather_facts: yes
  environment:
    http_proxy: "{{ lookup('env', 'PROXY') }}"
    https_proxy: "{{ lookup('env', 'PROXY') }}"
  vars:
    activemq_config_override_template: 'broker.xml.j2'
    activemq_jvm_package: java-11-openjdk-headless
    activemq_properties_file: test.properties
    activemq_version: 2.36.0
  roles:
    - middleware_automation.amq.activemq
