---
- name: Prepare
  hosts: all
  environment:
    http_proxy: "{{ lookup('env', 'PROXY') }}"
    https_proxy: "{{ lookup('env', 'PROXY') }}"
    no_proxy: "{{ lookup('env', 'NO_PROXY') }}"
  module_defaults:
    ansible.builtin.get_url:
      validate_certs: "{{ not lookup('env', 'PROXY') != '' }}"
  pre_tasks:
    - name: "Run preparation common to all scenario"
      ansible.builtin.include_tasks: ../prepare.yml
  tasks:
    - name: Include role for broker install
      ansible.builtin.include_role:
        name: middleware_automation.amq.activemq
      vars:
        activemq_version: "{{ '7.12.4' if amq_broker_enable is defined and amq_broker_enable else '2.36.0' }}"
