---
- name: Verify
  hosts: all
  become: "{{ activeamq_install_requires_become | default(true) }}"
  tasks:
    - name: Populate service facts
      ansible.builtin.service_facts:

    - name: Populate activemq facts
      middleware_automation.amq.activemq_facts:
        auth_username: amq
        auth_password: amqbrokerpass
        validate_certs: false

    - name: Print activemq gathered facts
      ansible.builtin.debug:
        var: ansible_facts.activemq

    - name: Check if amq-broker service is started
      ansible.builtin.assert:
        that:
          - ansible_facts.services["amq-broker.service"]["state"] == "running"
          - ansible_facts.services["amq-broker.service"]["status"] == "enabled"

    - name: Read content of logs
      ansible.builtin.slurp:
        src: /var/log/activemq/amq-broker/artemis.log
      register: slurped_log

    - name: Check status
      ansible.builtin.assert:
        that:
          - "'Server is now live' in slurped_log.content|b64decode or 'Server is now active' in slurped_log.content|b64decode"
        quiet: true
        fail_msg: "Service failed to start correctly"

    - name: Check ownership
      ansible.builtin.stat:
        path: /opt/amq/amq-broker/bin/
      register: broker_bin

    - name: Check ownership
      ansible.builtin.assert:
        that:
          - "broker_bin.stat.pw_name == 'amq-broker'"
        quiet: true
        fail_msg: "Wrong ownership of instance directories"

    - name: Retrieve users and roles from cli
      ansible.builtin.command: "/opt/amq/amq-broker/bin/artemis user list --user amq --password amqbrokerpass"
      changed_when: False
      register: user_roles

    - name: Verify users and roles
      ansible.builtin.assert:
        that:
          - "'\"other\"(producer,monitoring,consumer)' in user_roles.stdout"
          - "'\"amq\"(admin)' in user_roles.stdout"
          - "'\"business\"(specific)' in user_roles.stdout"
          - "'\"operator\"(operate)' in user_roles.stdout"
        quiet: true
        fail_msg: "Failed to retrieve configured users"

    - name: Check console redirect to login page
      ansible.builtin.uri:
        url: http://0.0.0.0:8161/console/
        follow_redirects: none
        status_code: 302
        headers:
          Origin: http://0.0.0.0

    - name: Check jolokia authenticated api call
      ansible.builtin.uri:
        url: 'http://0.0.0.0:8161/console/jolokia/read/org.apache.activemq.artemis:broker=!%22amq-broker!%22,component=acceptors,name=!%22artemis!%22/Started'
        user: amq
        password: amqbrokerpass
        force_basic_auth: yes
        status_code: 200
        headers:
          Origin: http://0.0.0.0
      register: this
      no_log: True

    - name: Check jolokia fine grained authentorization access
      ansible.builtin.uri:
        url: "{{ 'http://0.0.0.0:8161/console/jolokia/exec/' + operation.mbean }}"
        user: "{{ operation.user }}"
        password: "{{ operation.password }}"
        force_basic_auth: yes
        status_code: 200
        return_content: yes
        headers:
          Origin: http://0.0.0.0
      register: jolokia
      loop:
        - mbean: 'org.apache.activemq.artemis:broker=!%22amq-broker!%22,component=addresses,address=!%22queue.in!%22,subcomponent=queues,routing-type=!%22anycast!%22,queue=!%22queue.in!%22/browse()'
          user: amq
          password: amqbrokerpass
          result: 200
        - mbean: 'org.apache.activemq.artemis:broker=!%22amq-broker!%22,component=addresses,address=!%22queue.in!%22,subcomponent=queues,routing-type=!%22anycast!%22,queue=!%22queue.in!%22/browse()'
          user: other
          password: amqotherpass
          result: 200
        - mbean: 'org.apache.activemq.artemis:broker=!%22amq-broker!%22,component=addresses,address=!%22queue.in!%22,subcomponent=queues,routing-type=!%22anycast!%22,queue=!%22queue.in!%22/browse()'
          user: operator
          password: amqoperatorpass
          result: 403
        - mbean: 'org.apache.activemq.artemis:broker=!%22amq-broker!%22,component=addresses,address=!%22queue.in!%22,subcomponent=queues,routing-type=!%22anycast!%22,queue=!%22queue.in!%22/browse()'
          user: business
          password: amqbusinesspass
          result: 200
        - mbean: 'org.apache.activemq.artemis:broker=!%22amq-broker!%22,component=addresses,address=!%22other.queue.out!%22,subcomponent=queues,routing-type=!%22anycast!%22,queue=!%22other.queue.out!%22/browse()'
          user: amq
          password: amqbrokerpass
          result: 200
        - mbean: 'org.apache.activemq.artemis:broker=!%22amq-broker!%22,component=addresses,address=!%22other.queue.out!%22,subcomponent=queues,routing-type=!%22anycast!%22,queue=!%22other.queue.out!%22/browse()'
          user: other
          password: amqotherpass
          result: 200
        - mbean: 'org.apache.activemq.artemis:broker=!%22amq-broker!%22,component=addresses,address=!%22other.queue.out!%22,subcomponent=queues,routing-type=!%22anycast!%22,queue=!%22other.queue.out!%22/browse()'
          user: operator 
          password: amqoperatorpass
          result: 403
        - mbean: 'org.apache.activemq.artemis:broker=!%22amq-broker!%22,component=addresses,address=!%22other.queue.out!%22,subcomponent=queues,routing-type=!%22anycast!%22,queue=!%22other.queue.out!%22/browse()'
          user: business
          password: amqbusinesspass
          result: 403
        - mbean: 'org.apache.activemq.artemis:broker=!%22amq-broker!%22,component=addresses,address=!%22queue.in!%22,subcomponent=queues,routing-type=!%22anycast!%22,queue=!%22queue.in!%22/flushExecutor()'
          user: amq
          password: amqbrokerpass
          result: 200
        - mbean: 'org.apache.activemq.artemis:broker=!%22amq-broker!%22,component=addresses,address=!%22queue.in!%22,subcomponent=queues,routing-type=!%22anycast!%22,queue=!%22queue.in!%22/flushExecutor()'
          user: other
          password: amqotherpass
          result: 200
        - mbean: 'org.apache.activemq.artemis:broker=!%22amq-broker!%22,component=addresses,address=!%22queue.in!%22,subcomponent=queues,routing-type=!%22anycast!%22,queue=!%22queue.in!%22/flushExecutor()'
          user: operator 
          password: amqoperatorpass
          result: 403
        - mbean: 'org.apache.activemq.artemis:broker=!%22amq-broker!%22,component=addresses,address=!%22queue.in!%22,subcomponent=queues,routing-type=!%22anycast!%22,queue=!%22queue.in!%22/flushExecutor()'
          user: business
          password: amqbusinesspass
          result: 403
        - mbean: 'java.lang:type=Threading/getThreadCpuTime(%5BJ)/1'
          user: amq
          password: amqbrokerpass
          result: 200
        - mbean: 'java.lang:type=Threading/getThreadCpuTime(%5BJ)/1'
          user: other
          password: amqotherpass
          result: 200
        - mbean: 'java.lang:type=Threading/getThreadCpuTime(%5BJ)/1'
          user: operator 
          password: amqoperatorpass
          result: 200
        - mbean: 'java.lang:type=Threading/getThreadCpuTime(%5BJ)/1'
          user: business
          password: amqbusinesspass
          result: 403
      loop_control:
        loop_var: operation
        label: "{{ 'user \"' + operation.user + '\" form mBean \"' + operation.mbean + '\"'}}"
      failed_when: >
        ((jolokia.content | from_json).status | int) != (operation.result | int)
      no_log: true

    - name: Read content of artemis.profile
      ansible.builtin.slurp:
        src: /opt/amq/amq-broker/etc/artemis.profile
      register: slurped_artemis_profile

    - name: Check HAWTIO_ROLES or HAWTIO_ROLE
      block:
        - name: Check HAWTIO_ROLES (>= 2.40.0)
          ansible.builtin.assert:
            that:
              - >
                "HAWTIO_ROLES='admin,monitoring,operate,specific'" in slurped_artemis_profile.content | b64decode
            quiet: true
            fail_msg: "HAWTIO_ROLES not calculated correctly"
      rescue:
        - name: Check HAWTIO_ROLE (< 2.40.0)
          ansible.builtin.assert:
            that:
              - >
                "HAWTIO_ROLE='admin,monitoring,operate,specific'" in slurped_artemis_profile.content | b64decode
            quiet: true
            fail_msg: "HAWTIO_ROLE not calculated correctly"

    - name: Check diverts element exists in broker.xml
      community.general.xml:
        path: "/opt/amq/amq-broker/etc/broker.xml"
        xpath: /conf:configuration/core:core/core:diverts/core:divert
        input_type: xml
        state: present
        content: attribute
        namespaces:
          conf: urn:activemq
          core: urn:activemq:core
        pretty_print: yes
      register: diverts

    - name: Check created divert configuration
      ansible.builtin.assert:
        that:
          - diverts.count == 1
        quiet: true
        fail_msg: "Failed to retrieve generated divert"

    - name: Check divert configuration via jolokia
      ansible.builtin.assert:
        that:
          - ansible_facts.activemq.DivertNames | length > 0
          - ansible_facts.activemq.DivertNames | first == "TESTDIVERT"

    - name: Check queue configuration via jolokia
      ansible.builtin.assert:
        that:
          - ansible_facts.activemq.AddressNames | length > 0
          - "'client123.pubsub' in ansible_facts.activemq.AddressNames"
          - "'importantTopic' in ansible_facts.activemq.AddressNames"
