---
- name: Include install tasks
  ansible.builtin.include_tasks:
    file: systemd.yml
    apply:
      tags:
        - systemd
  tags:
    - systemd

- name: Include uninstall tasks
  ansible.builtin.include_tasks:
    file: uninstall.yml
    apply:
      tags:
        - uninstall
  tags:
    - uninstall
