---
- name: "Restart handler"
  ansible.builtin.include_tasks: restart.yml
  listen: "restart amq_broker"

- name: "Restart handler"
  ansible.builtin.include_tasks: restart.yml
  when: activemq_configuration_file_refresh_period | int < 1
  listen: "restart amq_broker with no config refresh"

- name: "Restart handler"
  ansible.builtin.file:
    path: "{{ activemq.instance_home }}/etc/broker.xml"
    state: touch
    owner: "{{ activemq_service_user }}"
    group: "{{ activemq_service_group }}"
    mode: '0644'
  become: "{{ activemq_install_requires_become | default(true) }}"
  listen: "touch broker.xml"

- name: "Start handler"
  ansible.builtin.include_tasks: start.yml
  listen: "start amq_broker"

- name: "Stop handler"
  ansible.builtin.include_tasks: stop.yml
  listen: "stop amq_broker"
