---
name: CI
on:
  push:
    branches:
      - AMW-373
  pull_request:
  workflow_dispatch:
    inputs:
      debug_verbosity:
        description: 'ANSIBLE_VERBOSITY envvar value'
        required: false
  schedule:
    - cron: '0 6 * * *'

jobs:
  ci:
    uses: ansible-middleware/github-actions/.github/workflows/cish.yml@rootperm
    secrets: inherit
    with:
      fqcn: 'middleware_automation/amq'
      debug_verbosity: "${{ github.event.inputs.debug_verbosity }}"
      root_permission_varname: activemq_install_requires_become
      molecule_tests: >-
        [ "static_cluster", "replication", "live_only", "mirroring", "amq_upgrade" ]
      podman_tests_current: >-
        [ "default", "custom_xml", "federation", "mask_passwords", "uninstall" ]
      podman_tests_next: >-
        [ "default", "custom_xml", "federation", "mask_passwords", "uninstall" ]
